import { Suspense } from 'react'
import NavBar from './components/NavBar'
import Provider from './context/AuthContext'
import ToasterContext from './context/ToastContext'
import './globals.css'
import Loading from './loading'

export const metadata = {
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-[#06142B] via-[#0B1F3D] to-[#06142D] text-gray-50">
        <Provider>
          <ToasterContext />
          <Suspense fallback={<Loading />}>
            <NavBar />
            {children}
          </Suspense>
        </Provider>
      </body>
    </html>
  )
}
